server:
  port: 9990
spring:
  application:
    name: eureka-client
eureka:
  client:
    healthcheck.enabled: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    ##指注册中心从它的视图中删除此服务之前接收到最后一次心跳的等待时间，以秒为单位
    lease-expiration-duration-in-seconds: 4
    ##该服务需要多长时间（以秒为单位)向eureka注册中心发送检测信号以指示它仍然存在。
    ##如果在leaseExpirationDurationInSeconds中指定的时间段内没有收到检测信号，
    ##则注册中心将从其视图中删除该服务
    lease-renewal-interval-in-seconds: 3
